apiVersion: v1
kind: Service
metadata:
  name: test1
spec:
  selector:
    app: test1
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: test1
        image: 211.183.3.100/hk-repo/repository:jiho
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: regsec
