apiVersion: v1
kind: Service
metadata:
  name: myapp1
spec:
  selector:
    app: myapp1
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: myapp1
        image: jiho9898/projectlab:jiho
        ports:
        - containerPort: 80
